steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}', '.']

- name: 'docker/compose:1.15.0'
  args: ['up', '-d']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:integration']
  env:
  - 'HOST=nginx' # name of the running container
  - 'PORT=50051'
images: ['gcr.io/$PROJECT_ID/${_IMAGE}']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/${_DEPLOYMENT}', '$_CONTAINER=gcr.io/$PROJECT_ID/${_IMAGE}']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
# images:
# - 'gcr.io/$PROJECT_ID/${_IMAGE}'
# substitutions:
#   _CLUSTER: cloudbuildtest
#   _ZONE: us-central1-a
#   _IMAGE: example-image
#   _CONTAINER: nginx
#   _DEPLOYMENT: cloud-build-test