steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image2', '.']
  dir: 'subdirectory'
images: ['gcr.io/$PROJECT_ID/image1', 'gcr.io/$PROJECT_ID/image2']
# steps:
# - name: gcr.io/cloud-builders/gcloud
#   args: ['source', 'repos', 'clone', 'default']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/${_DEPLOYMENT}', 'my-container=gcr.io/$PROJECT_ID/${_IMAGE}']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
# images:
# - 'gcr.io/$PROJECT_ID/${_IMAGE}'