steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/testpush_image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testpush_image']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/testpush', 'my-container=gcr.io/$PROJECT_ID/testpush_image']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-test-cluster'
# images: ['gcr.io/$PROJECT_ID/testpushimage']