# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}_$BUILD_ID', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}_$BUILD_ID']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/${_DEPLOYMENT}', 'my-container=gcr.io/$PROJECT_ID/${_IMAGE}_$BUILD_ID']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
# images: ['gcr.io/$PROJECT_ID/testpushimage']

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE}:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE}:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENT}'
  - 'my-container=gcr.io/$PROJECT_ID/${_IMAGE}:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'