steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'example', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'example']

# my-image is pushed to Container Registry
# images:
# - 'gcr.io/$PROJECT_ID/my-image'
# steps:
# - name: gcr.io/cloud-builders/gcloud
#   args: ['source', 'repos', 'clone', 'default']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/${_DEPLOYMENT}', '$_CONTAINER=gcr.io/$PROJECT_ID/${_IMAGE}']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
# images:
# - 'gcr.io/$PROJECT_ID/${_IMAGE}'
# substitutions:
#   _CLUSTER: cloudbuildtest
#   _ZONE: us-central1-a
#   _IMAGE: example-image
#   _CONTAINER: nginx
#   _DEPLOYMENT: cloud-build-test
# - name: gcr.io/cloud-builders/git
#   args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']

#docker-compose exec web bash -c "cd /var/www/html/jackercleaning/ && ./vendor/bin/phpunit"